import { ScheduledEvent } from '@/types';

export const MOCK_EVENTS: ScheduledEvent[] = [
  {
    id: '1',
    platform: 'instagram',
    actionType: 'reel',
    caption: 'Weekend vibes ✨',
    hashtags: '#weekend #vibes #life',
    scheduledAt: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    status: 'SCHEDULED',
    executionMode: 'MANUAL_REMINDER',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    platform: 'whatsapp',
    actionType: 'message',
    recipient: 'John',
    message: 'Good night bro 😂',
    scheduledAt: new Date(Date.now() + 4.5 * 60 * 60 * 1000).toISOString(),
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    status: 'SCHEDULED',
    executionMode: 'MANUAL_REMINDER',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    platform: 'facebook',
    actionType: 'post',
    caption: 'Monday motivation 💪',
    scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    status: 'SCHEDULED',
    executionMode: 'AUTOMATIC',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    platform: 'instagram',
    actionType: 'story',
    caption: 'Behind the scenes 🎬',
    scheduledAt: new Date(Date.now() + 25 * 60 * 60 * 1000).toISOString(),
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    status: 'SCHEDULED',
    executionMode: 'MANUAL_REMINDER',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    platform: 'tiktok',
    actionType: 'video',
    caption: 'Check out this hack 🔥',
    hashtags: '#hack #tips #tiktok',
    scheduledAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    status: 'SCHEDULED',
    executionMode: 'MANUAL_REMINDER',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_COMPLETED_EVENTS: ScheduledEvent[] = [
  {
    id: 'c1',
    platform: 'instagram',
    actionType: 'reel',
    caption: 'Summer vibes 🌊',
    hashtags: '#summer #beach #vibes',
    scheduledAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    status: 'COMPLETED',
    executionMode: 'MANUAL_REMINDER',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c2',
    platform: 'facebook',
    actionType: 'post',
    caption: 'Great day today!',
    scheduledAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    status: 'COMPLETED',
    executionMode: 'AUTOMATIC',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c3',
    platform: 'tiktok',
    actionType: 'video',
    caption: 'Duet this!',
    scheduledAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    status: 'FAILED',
    executionMode: 'MANUAL_REMINDER',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    errorMessage: 'API connection failed',
  },
  {
    id: 'c4',
    platform: 'instagram',
    actionType: 'post',
    caption: 'Coffee time ☕',
    hashtags: '#coffee #morning',
    scheduledAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    status: 'CANCELLED',
    executionMode: 'MANUAL_REMINDER',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
