import { SocialPlatform } from '@/types';

export const PLATFORMS: SocialPlatform[] = [
  {
    id: 'instagram',
    name: 'Instagram',
    color: '#E4405F',
    connected: false,
    icon: 'instagram',
    capabilities: [
      {
        actionType: 'post',
        label: 'Post',
        description: 'Share a photo or carousel',
        requiresMedia: true,
        supportsCaption: true,
        supportsHashtags: true,
        supportsMediaAttach: false,
        executionMode: 'AUTOMATIC',
      },
      {
        actionType: 'reel',
        label: 'Reel',
        description: 'Share a short video',
        requiresMedia: true,
        supportsCaption: true,
        supportsHashtags: true,
        supportsMediaAttach: false,
        executionMode: 'MANUAL_REMINDER',
      },
      {
        actionType: 'story',
        label: 'Story',
        description: 'Share a temporary story',
        requiresMedia: true,
        supportsCaption: false,
        supportsHashtags: false,
        supportsMediaAttach: false,
        executionMode: 'MANUAL_REMINDER',
      },
      {
        actionType: 'message',
        label: 'Message',
        description: 'Send a direct message',
        requiresMedia: false,
        supportsCaption: false,
        supportsHashtags: false,
        supportsMediaAttach: true,
        executionMode: 'MANUAL_REMINDER',
      },
    ],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    color: '#010101',
    connected: false,
    icon: 'tiktok',
    capabilities: [
      {
        actionType: 'video',
        label: 'Video',
        description: 'Share a video',
        requiresMedia: true,
        supportsCaption: true,
        supportsHashtags: true,
        supportsMediaAttach: false,
        executionMode: 'MANUAL_REMINDER',
      },
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    color: '#1877F2',
    connected: false,
    icon: 'facebook',
    capabilities: [
      {
        actionType: 'post',
        label: 'Post',
        description: 'Share a post',
        requiresMedia: false,
        supportsCaption: true,
        supportsHashtags: false,
        supportsMediaAttach: true,
        executionMode: 'AUTOMATIC',
      },
      {
        actionType: 'video',
        label: 'Video',
        description: 'Share a video',
        requiresMedia: true,
        supportsCaption: true,
        supportsHashtags: false,
        supportsMediaAttach: false,
        executionMode: 'MANUAL_REMINDER',
      },
      {
        actionType: 'story',
        label: 'Story',
        description: 'Share a story',
        requiresMedia: true,
        supportsCaption: false,
        supportsHashtags: false,
        supportsMediaAttach: false,
        executionMode: 'MANUAL_REMINDER',
      },
    ],
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    color: '#25D366',
    connected: false,
    icon: 'whatsapp',
    capabilities: [
      {
        actionType: 'message',
        label: 'Message',
        description: 'Send a message',
        requiresMedia: false,
        supportsCaption: false,
        supportsHashtags: false,
        supportsMediaAttach: true,
        executionMode: 'MANUAL_REMINDER',
      },
    ],
  },
];
